### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by jjscheel** [riscv/riscv-platform-specs#18]
While the [README](https://github.com/riscv/riscv-platform-specs/blob/main/README.md) file references the project is licensed under the CC-BY-4.0 license and provides a link to the full license text. the lack of a LICENSE file prevent GitHub from recognizing the license.

I propose adding a plain text [LICENSE ](https://github.com/riscv/riscv-isa-manual/blob/master/LICENSE) file like the one used in the ISA manual.

I'm happy to add this into the project directly and will do so shortly. If anyone has concerns, please raise them.

Thanks,
-Jeff

**Comment by vlsunil** [comment]
@jjscheel : Yes, please go ahead. Thanks!

**Comment by jjscheel** [comment]
@vlsunil, I've added the new file.  After another look at the licensing.adoc, I think we should move the Copyright information somewhere, perhaps back into the README.  I don't think we want to lose that information.

Do you want to take care of that?  I'm happy to do it if you'd prefer.

I'll leave this open until we decide.

**Comment by kumarsankaran** [comment]
Is this issue resolved?

**Comment by jjscheel** [comment]
@kumarsankaran, I still see the licensing.adoc file in the tree and the text in it is not in the README.  So, I'd say that this is not done.

I'm happy to complete the work if you'd prefer.

**Comment by kumarsankaran** [comment]
Yes, please Jeff. Can you complete what's needed and close this issue?

**Comment by jjscheel** [comment]
On retrospect, the licensing.adoc file should be part of the document, not the site.

@kumarsankaran, I don't see license info in the document.  I believe it should be there, do you agree?

**Comment by kumarsankaran** [comment]
@jjscheel Yes, the licensing info should be there in the document.

**Comment by jjscheel** [comment]
@kumarsankaran, when I review the last published [riscv-platform-spec](https://github.com/riscv/riscv-platform-specs/blob/main/riscv-platform-spec.pdf) from Nov 1, I don't see the licensing information nor the changelog nor the contributor.  While I'm not yet an expert in asciidoc, I suspect that you failing to include these in your top file (riscv-platform-spec.adoc).  I see them listed in the Makefile as $PARTS and see where that file starts the build in the top file, but I don't see any additional include files.

I'll let you folks hand this as you want.  You can either continue to work it here, or open a new issuse and close this one.

Sound ok?

**Comment by jjscheel** [comment]
I see that these have now been included.  Closing.
