### ISSUE TITLE
RVM platform requirements

### ISSUE THREAD

**Issue by tovine** [riscv/riscv-platform-specs#25]
Great initiative!  
I do however have questions about the requirements for the RVM platform, specifically the 32-bit version;

Is it realistic to require RV32G in order to comply with the RVM platform? It seems like a more natural choice would be RV32IMAF, as RV32D is pretty heavy on the floating-point for small microcontrollers (most Cortex-M devices don't even have double precision support in hardware, that's only available in the M55 and M7).

Also the C extension would make sense to include as embedded applications are quite sensitive to code size, but that's probably a different discussion worthy of its own issue...

**Comment by atishp04** [comment]
The M Platform must comply with the RVM22M profile defined by the RISC-V profiles specification.
This discussion should happen in profile specification as platform specification will just mandate the RVM22M profile.
Closing this issue for now.
