### ISSUE TITLE
relax "If Hypervisor extension is supported then the misa.H bit must be writable."

### ISSUE THREAD

**Issue by ingallsj** [riscv/riscv-platform-specs#54]
> `misa`
> If H extension is supported then the H bit must be writable.

For example, open-source Rocket-chip does not (yet): https://github.com/chipsalliance/rocket-chip/pull/2841

**Comment by aswaterman** [comment]
See also discussion thread https://lists.riscv.org/g/tech-privileged/message/851

**Comment by atishp04** [comment]
We can close this issue as the current spec doesn't have this text anymore.
