### ISSUE TITLE
relax RAS precise exception on uncorrectable data

### ISSUE THREAD

**Issue by ingallsj** [riscv/riscv-platform-specs#55]
The platform spec includes this proposed requirement:

> Attempted use of corrupted (uncorrectable) data must result in a precise exception on that instruction with a distinguishing custom exception cause code.

This adds a non-trivial performance/area cost, and is a stronger requirement than other contemporary ISAs and system architectures.

**Comment by aswaterman** [comment]
I've also discussed this one with @gfavor and @kasanovic... our current thinking is that the ISA must prove a way for software to determine whether the exception was precise or imprecise (e.g., by different cause codes, possibly exception vs. interrupt).  This approach covers both bases.

**Comment by atishp04** [comment]
This requirement has been relaxed. Closing this issue.
