### ISSUE TITLE
I/O ordering requirements (for non-PCIe devices)

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-platform-specs#77]
The OS-A platform spec used to have a requirement for strong point-to-point I/O ordering for most devices.  It was deleted last year with the remark "All the points specified in supervisor.adoc are already described in the new revamped platform spec", but I cannot find any statement to this effect.  The change was here: https://github.com/riscv/riscv-platform-specs/commit/3e12ad108b74b2852d8a8540350287114cb80174#diff-1d563824326d2cf24a223ae5c45f6247f5fd9a553acff627370ddd8f9e64b031L16-L17

I think we just need to add the following clause: "Unless otherwise specified by a given I/O device, I/O devices are on ordering channel 0 (i.e., they are point-to-point strongly ordered)."

I see that there are now some different requirements for PCIe.  That's OK; these statements don't conflict, because of the "unless otherwise specified" phrase.

**Comment by kumarsankaran** [comment]
Added this to PCIe section of the spec.
Thank You.

**Comment by aswaterman** [comment]
@kumarsankaran I'm reopening this issue to ask that you _not_ place it in the PCIe section.  It is meant to apply to I/O devices in general (including things like PLIC/CLINT registers).  Maybe put it in the ISA requirements section (4.1.1)?

**Comment by kumarsankaran** [comment]
@aswaterman Since this applies to all IO devices and is a common requirement for all platforms, it would go into the ISA Requirements sub-section 2.1.1 within the OS-A Common Requirements section.
The OS-A Server Platform inherits all the requirements as defined in the OS-A Platform Common Requirements section.

**Comment by aswaterman** [comment]
My mistake, yeah, 2.1.1 is the right place.

**Comment by kumarsankaran** [comment]
Moved to section 2.1.1.
Closing. Thank You.

**Comment by aswaterman** [comment]
Thank you!
